### PR TITLE
Prevent two modals being shown at once.

### PR DESCRIPTION
**Pull request by adriaanwm**

### CODE REVIEW

**Comment by staydecent** [comment]
How would this be replicated? If you called Modals twice with the same child under it?

```
      <Modals>
        <ExampleModal />
      </Modals>
      <Modals>
        <ExampleModal />
      </Modals>
```

@adriaanwm

**Comment by adriaanwm** [comment]
It happened in vericlock when there was a modal already (publish draft with conflicts) and then you click delete one of the shift's. It would open another modal on top. Seems like a Portal bug tbh. This fixed it and didn't want to spend anymore time digging into Portal.

**Comment by staydecent** [comment]
Strange, I created some tests and can't replicate having two modals render: https://github.com/inputlogic/elements/pull/86/files

There must be some edge case occurring in vericlock..

**Comment by adriaanwm** [comment]
@staydecent you can replicate it by going to vericlock on time period with draft shift that conflicts, and selecting publish, then selecting delete inside the publish modal.

**Comment by coryschadt** [comment]
Demo of issue: 
double-modal

**Review by staydecent — APPROVED** [review]

**Pull request merged**
