### PR TITLE
Support fully customized date select.

### PR DESCRIPTION
**Pull request by adriaanwm**

### CODE REVIEW

**Comment by adriaanwm** [comment]
Wish there was a way to quickly install the component from this branch to verify the changes.

**Comment by staydecent** [comment]
> Wish there was a way to quickly install the component from this branch to verify the changes.

I think this is still a limitation of monorepos. unless you git submoduled this whole repo and then aliases the component to it's submoduled directory...

I still just edit the node_modules/@app-elements/date-picker in my current project.

**Comment by staydecent** [comment]
Screen Shot 2020-03-26 at 12 07 57 PM

Are there any other details that prevent matching the legendaily calendar style other than the markup for the month header and the day of the week headers?

If the month header text and the next/prev month buttons where on the same flex-box level, then you could override their order without HTML changes.

And if we add a prop for day of week header strings, then those can be customized.

The rest should be doable with CSS, no?

@adriaanwm

**Comment by adriaanwm** [comment]
Yeah I think those are the parts that I can't do with css.
- order of header elements
- icons for change month arrows
- day text (S -> Su)

I guess it comes down to if we want props to keep changing to support different requirements, or just have a way to override the markup. I like overriding the markup since, to me, the value of a date picker component is not having to worry about all the date related stuff. Adding markup and styling from scratch is no more difficult than overriding existing stuff 🤷‍♂

**Review by staydecent — APPROVED** [review]
💎

**Pull request merged**
